server {
    listen 80;
    # listen 443 ssl;
    server_name ourstory.cloud www.ourstory.cloud localhost;

    ssl_certificate /etc/letsencrypt/live/ourstory.cloud/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/ourstory.cloud/privkey.pem;

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }

}

server {
    listen 456 ssl;
    server_name srv642680.hstgr.cloud;

    ssl_certificate /etc/letsencrypt/live/srv642680.hstgr.cloud/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/srv642680.hstgr.cloud/privkey.pem;

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }
}